"""initial tables

Revision ID: b0ba5d02df63
Revises: 
Create Date: 2026-09-22 00:27:51.083841
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = 'b0ba5d02df63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessibility_locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_accessibility_locations_geom', 'accessibility_locations', ['geom'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_table('traffic_segments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('road_name', sa.String(length=255), nullable=False),
    sa.Column('speed_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_traffic_segments_geom', 'traffic_segments', ['geom'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('commuter', 'admin', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True, if_not_exists=True)
    op.create_table('accessibility_photos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('contributor_id', sa.String(length=36), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contributor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['accessibility_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessibility_photos_location_id'), 'accessibility_photos', ['location_id'], unique=False, if_not_exists=True)
    op.create_table('route_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('origin', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('destination', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_route_requests_destination', 'route_requests', ['destination'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index('idx_route_requests_origin', 'route_requests', ['origin'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index(op.f('ix_route_requests_user_id'), 'route_requests', ['user_id'], unique=False, if_not_exists=True)
    op.create_table('traffic_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('segment_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['traffic_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_observations_segment_id'), 'traffic_observations', ['segment_id'], unique=False, if_not_exists=True)
    op.create_table('traffic_predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('segment_id', sa.String(length=36), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('predicted_speed', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['traffic_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_predictions_segment_id'), 'traffic_predictions', ['segment_id'], unique=False, if_not_exists=True)
    op.create_table('accessibility_detections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('photo_id', sa.String(length=36), nullable=False),
    sa.Column('feature_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox', sa.Text(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['accessibility_photos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessibility_detections_photo_id'), 'accessibility_detections', ['photo_id'], unique=False, if_not_exists=True)
    op.create_table('route_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('route_geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('travel_time', sa.Float(), nullable=False),
    sa.Column('delay', sa.Float(), nullable=False),
    sa.Column('emissions', sa.Float(), nullable=False),
    sa.Column('accessibility_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['route_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_route_results_route_geom', 'route_results', ['route_geom'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index(op.f('ix_route_results_request_id'), 'route_results', ['request_id'], unique=False, if_not_exists=True)
    # NOTE: autogen DDL for PostGIS/tiger-geocoder extension tables removed (owned by extensions)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogen DDL for PostGIS/tiger-geocoder extension tables removed (owned by extensions)
    op.drop_index(op.f('ix_route_results_request_id'), table_name='route_results')
    op.drop_index('idx_route_results_route_geom', table_name='route_results', postgresql_using='gist')
    op.drop_table('route_results')
    op.drop_index(op.f('ix_accessibility_detections_photo_id'), table_name='accessibility_detections')
    op.drop_table('accessibility_detections')
    op.drop_index(op.f('ix_traffic_predictions_segment_id'), table_name='traffic_predictions')
    op.drop_table('traffic_predictions')
    op.drop_index(op.f('ix_traffic_observations_segment_id'), table_name='traffic_observations')
    op.drop_table('traffic_observations')
    op.drop_index(op.f('ix_route_requests_user_id'), table_name='route_requests')
    op.drop_index('idx_route_requests_origin', table_name='route_requests', postgresql_using='gist')
    op.drop_index('idx_route_requests_destination', table_name='route_requests', postgresql_using='gist')
    op.drop_table('route_requests')
    op.drop_index(op.f('ix_accessibility_photos_location_id'), table_name='accessibility_photos')
    op.drop_table('accessibility_photos')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_traffic_segments_geom', table_name='traffic_segments', postgresql_using='gist')
    op.drop_table('traffic_segments')
    op.drop_index('idx_accessibility_locations_geom', table_name='accessibility_locations', postgresql_using='gist')
    op.drop_table('accessibility_locations')
    # ### end Alembic commands ###
